### ISSUE TITLE
try_reserve tests execute UB, will fail in Rust 1.82

### ISSUE THREAD

**Issue by saethlin** [LeonineKing1199/minivec#34] opened 2024-09-20 21:23 UTC
I am filing this issue because this project's tests failed in the crater runs for Rust 1.82: https://github.com/rust-lang/rust/issues/130579, you can reproduce this failure with cargo +beta test or cargo +nightly test.

There is some interesting wording in the failing test: https://github.com/cmazakas/minivec/blob/7573a5428bb282175b6e7ee958e000ea504911b8/tests/vec.rs#L1600-L1603

You cannot rely on the underlying allocator to fail in this scenario. Even if the allocator does fail, the execution encounters UB before the abort due to allocation failure, so it is technically wrong to rely on the allocator failing.

**Comment by cmazakas** [comment] 2024-09-22 18:12
The actual test failure seemed to have been caused by an update to Layout. I've updated the code now.

I'm not sure where there's any UB tho. This test is a copy-paste of the stdlib test so I just do whatever they do. If they do UB, I do UB.

But I really do appreciate you calling my attention to the test failure. Been a hot minute since I've touched the code. The ping is much appreciated.

Closing because the failing test is now technically fixed `cargo --nightly miri test && cargo --nightly test` seems to pass fine.

**Closed as completed by cmazakas** 2024-09-22 18:12 UTC

**Comment by saethlin** [comment] 2024-09-22 18:21
> The actual test failure seemed to have been caused by an update to Layout.

Yeah, by me. I added a special kind of debug assertion to it. It looks like the standard library code was changed in https://github.com/rust-lang/rust/pull/95295, thanks for the heads-up that you pasted this test from the standard library. Some quick GitHub code search suggests a lot of other people have too :upside_down_face:
